# Generated by Django 5.0.1 on 2024-01-31 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={},
        ),
    ]
