# Generated by Django 5.0.1 on 2024-01-31 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttapp', '0002_alter_staff_options_alter_timetable_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={},
        ),
    ]
